# Generated by Django 4.1.1 on 2022-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons_text',
            options={'ordering': ['id'], 'verbose_name': 'Описание уроков', 'verbose_name_plural': 'Описание уроков'},
        ),
        migrations.AddField(
            model_name='lessons_text',
            name='code',
            field=models.CharField(choices=[('Код', True), ('Текст', False)], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
