# Generated by Django 4.1.1 on 2022-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lessons_text_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_text',
            name='code',
            field=models.CharField(choices=[('Yes', True), ('No', False)], max_length=10, verbose_name='Код?'),
        ),
    ]
