# Generated by Django 4.1.1 on 2022-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lessons_text_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_text',
            name='code',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No')], max_length=10, verbose_name='Код?'),
        ),
    ]
