# Generated by Django 4.1.1 on 2022-11-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lessons_text_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='dop_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация о курсе'),
        ),
        migrations.AlterField(
            model_name='lessons_text',
            name='code',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=10, verbose_name='Код?'),
        ),
    ]
