# Generated by Django 4.1.1 on 2022-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_curs_dop_info_alter_lessons_text_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons_text',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='curs/', verbose_name='Фото к тексту'),
        ),
        migrations.AlterField(
            model_name='lessons_text',
            name='code',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Photo')], max_length=10, verbose_name='Код?'),
        ),
        migrations.AlterField(
            model_name='lessons_text',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст урока'),
        ),
    ]
